language: php

sudo: false

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

cache:
  directories:
    - $HOME/.composer/cache/files
